[package]
name = "rucc"
version = "0.2.1"
authors = ["uint256_t"]

[dependencies]
llvm-sys = "100.0.0"

lazy_static = "1.4.0"

regex = "0.2.1"

rand = "0.3"

clap = "2.29"

ansi_term = "0.9.0"

libc = "*"

